SearchSpace:
  type: LayersBased
  layers_types: [Conv2d, MaxPool2d, Dropout, ReLU]
  layers_count: [5, 7]
  channels: [3, 5, 8, 16]
  kernel: [2, 3, 5]
  padding: [0, 1, 2]
  last_hid_mlp: [0, 50, 100, 128]
  dropout_rates: [0.1, 0.3, 0.5]

SearchStrategy:
  type: EvolutionarySearch
  population_size: 4
  generations: 3

ValidationStrategy:
  type: FullTraining
  optimizer: Adam
  optimizer_params: {lr: 0.01}
  epochs: 10
  metrics: [acc_val]
  trn_data: {url: mnist_train.csv, batch: 32}
  val_data: {url: mnist_test.csv, batch: 64}